# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: bedag
name: nfv
version: 0.1.0
readme: README.md
authors:
  - Kevin Klopfenstein (github.com/chifu1234)
description: "Collection for bedag network function virtualizations"
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - bedag
  - bgp
  - exabgp
  - anycast
repository: https://github.com/bedag/ansible-galaxy
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/bedag/ansible-galaxy
issues: https://github.com/bedag/ansible-galaxy/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
